services:
  # ====================================================================================================
  # Server ( Next.js )
  # ====================================================================================================
  notes_server:
    container_name: notes_server_prod
    build:
      context: ..
      dockerfile: docker/Dockerfile.prod
    ports:
      - "7001:7000"
    stdin_open: true
    tty: true
    env_file:
      - ../envs/.env.prod

  # ====================================================================================================
  # Database ( Neon )
  # ====================================================================================================
  # ...

  # ====================================================================================================
  # Object Storage
  # ====================================================================================================
  # ...

  # ====================================================================================================
  # Redis
  # ====================================================================================================
  # ...
