services:
  # ====================================================================================================
  # Server ( Next.js )
  # ====================================================================================================
  notes_server:
    container_name: notes_server
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
    ports:
      - "7000:7000"
    stdin_open: true
    tty: true
    depends_on:
      notes_db:
        condition: service_healthy
    env_file:
      - ../envs/.env.dev
    networks:
      - venomous-notes-network
    volumes:
      - ../:/usr/src/app
      # - /usr/src/app/node_modules

  # ====================================================================================================
  # Database ( PostgreSQL )
  # ====================================================================================================
  notes_db:
    image: postgres:13.3
    container_name: notes_db
    hostname: notes_db
    restart: always
    ports:
      - "7100:5432"
    env_file:
      - ../envs/.env.dev
    networks:
      - venomous-notes-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d venomous_notes_db"]
      interval: 5s
      timeout: 2s
      retries: 20
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # ====================================================================================================
  # Prisma Studio
  # ====================================================================================================
  prisma_studio:
    container_name: notes_prisma_studio
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
    working_dir: /usr/src/app
    command: sh -c "\
      npx prisma db push && \
      npx prisma studio --hostname 0.0.0.0 --port 7200 --browser none
      "
    ports:
      - "7200:7200"
    env_file:
      - ../envs/.env.dev
    networks:
      - venomous-notes-network
    depends_on:
      notes_db:
        condition: service_healthy
      notes_server:
        condition: service_started
    volumes:
      - ../:/usr/src/app
      - /usr/src/app/node_modules

  # ====================================================================================================
  # Object Storage ( MinIO )
  # ====================================================================================================
  minio:
    image: minio/minio
    container_name: notes_minio
    command: server /data --console-address ":9001"
    env_file:
      - ../envs/.env.dev
    ports:
      - "7300:9000"
      - "7301:9001" # console
    volumes:
      - notes_minio_data:/data

  # ====================================================================================================
  # Redis
  # ====================================================================================================
  # ...

networks:
  venomous-notes-network:
    name: venomous-notes-network

volumes:
  postgres_data: {}
  notes_minio_data: {}
