services:
  # Server ( Next.js )
  # ====================================================================================================
  notes_server:
    container_name: notes_server_prod
    build:
      context: ..
      dockerfile: docker/Dockerfile.prod
    ports:
      - "7001:7000"
    stdin_open: true
    tty: true
    environment:
      DATABASE_URL: "postgresql://neondb_owner:npg_JBhduY0C7xaI@ep-dark-sun-a46gef1s-pooler.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require"

  # Database ( Neon )
  # ====================================================================================================
