services:
  # Server ( Next.js )
  # ====================================================================================================
  notes_server:
    container_name: notes_server
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
    ports:
      - "7000:7000"
    stdin_open: true
    tty: true
    depends_on:
      notes_db:
        condition: service_healthy
    environment:
        DATABASE_URL: "postgresql://postgres:postgres@notes_db:5432/venomous_notes_db?schema=public"
    networks:
      - venomous-notes-network
    volumes:
      - ../:/usr/src/app
      - /usr/src/app/node_modules

  # Database ( PostgreSQL )
  # ====================================================================================================
  notes_db:
    image: postgres:13.3
    container_name: notes_db
    hostname: notes_db
    restart: always
    environment:
      POSTGRES_DB: venomous_notes_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "7100:5432"
    networks:
      - venomous-notes-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d venomous_notes_db"]
      interval: 5s
      timeout: 2s
      retries: 20
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Prisma Studio
  # ====================================================================================================
  prisma_studio:
    container_name: notes_prisma_studio
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
    working_dir: /usr/src/app
    command: sh -c "\
      npx prisma db push && \
      npx prisma studio --hostname 0.0.0.0 --port 7200 --browser none
      "
    ports:
      - "7200:7200"
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@notes_db:5432/venomous_notes_db?schema=public"
    networks:
      - venomous-notes-network
    depends_on:
      notes_db:
        condition: service_healthy
      notes_server:
        condition: service_started
    volumes:
      - ../:/usr/src/app
      - /usr/src/app/node_modules

networks:
  venomous-notes-network:
    name: venomous-notes-network

volumes:
  postgres_data: {}
